import type { OperatorDefinition, OperatorRole } from "./types";

export const roleLabels: Record<OperatorRole, string> = {
  guard: "近卫",
  defender: "重装",
  caster: "术师",
  sniper: "狙击",
  medic: "医疗",
  specialist: "特种",
};

export const roleColors: Record<OperatorRole, string> = {
  guard: "#e85858",
  defender: "#6f8faf",
  caster: "#a66dff",
  sniper: "#f0a53a",
  medic: "#42c97b",
  specialist: "#41c9d6",
};

export const operators: OperatorDefinition[] = [
  {
    id: "amiya",
    name: "阿米娅",
    englishName: "Amiya",
    role: "caster",
    attackMode: "ranged",
    maxHp: 1480,
    attack: 612,
    defense: 121,
    resistance: 20,
    damageType: "arts",
    attackInterval: 1.6,
    attackRangeId: "amiyaDefault",
    rangeTileSize: 54,
    radius: 30,
    speed: 176,
    spRegen: 1,
    spRecoveryType: "natural",
    skillId: "chimera",
  },
  {
    id: "chen",
    name: "陈",
    englishName: "Chen",
    role: "guard",
    attackMode: "melee",
    maxHp: 28800,
    attack: 610,
    defense: 352,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1.3,
    attackRangeId: "chenDefault",
    rangeTileSize: 64,
    radius: 31,
    speed: 188,
    spRegen: 0,
    spRecoveryType: "attack",
    attackMultiplier: 1.05,
    defenseMultiplier: 1.05,
    physicalDodge: 0.1,
    skillId: "sheathStrike",
  },
  {
    id: "hoshiguma",
    name: "星熊",
    role: "defender",
    attackMode: "melee",
    maxHp: 2050,
    attack: 76,
    defense: 62,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1.6,
    attackRangeId: "forwardShort",
    rangeTileSize: 64,
    radius: 34,
    speed: 142,
    spRegen: 12,
    spRecoveryType: "natural",
    skillId: "ironWall",
  },
  {
    id: "exusiai",
    name: "能天使",
    englishName: "Exusiai",
    role: "sniper",
    attackMode: "ranged",
    maxHp: 16730,
    attack: 540,
    defense: 161,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1,
    attackRangeId: "exusiaiDefault",
    rangeTileSize: 56,
    radius: 27,
    speed: 212,
    spRegen: 1,
    spRecoveryType: "natural",
    attackSpeedBonus: 12,
    attackMultiplier: 1.06,
    maxHpMultiplier: 1.1,
    skillId: "exusiaiOverloadMode",
  },
  {
    id: "saria",
    name: "塞雷娅",
    role: "medic",
    attackMode: "melee",
    maxHp: 1760,
    attack: 70,
    defense: 52,
    resistance: 10,
    damageType: "physical",
    attackInterval: 1.8,
    attackRangeId: "forwardShort",
    rangeTileSize: 64,
    radius: 33,
    speed: 150,
    spRegen: 15,
    spRecoveryType: "natural",
    skillId: "firstAid",
  },
  {
    id: "phantom",
    name: "傀影",
    role: "specialist",
    attackMode: "melee",
    maxHp: 1260,
    attack: 91,
    defense: 24,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1.1,
    attackRangeId: "forwardShort",
    rangeTileSize: 64,
    radius: 28,
    speed: 238,
    spRegen: 20,
    spRecoveryType: "natural",
    skillId: "shadowPush",
  },
];

for (const operator of operators) {
  if (operator.id !== "chen" && operator.id !== "exusiai") {
    operator.maxHp *= 10;
  }
}
