import type { OperatorDefinition, OperatorRole } from "./types";

export const roleLabels: Record<OperatorRole, string> = {
  guard: "近卫",
  defender: "重装",
  caster: "术师",
  sniper: "狙击",
  medic: "医疗",
  specialist: "特种",
};

export const roleColors: Record<OperatorRole, string> = {
  guard: "#e85858",
  defender: "#6f8faf",
  caster: "#a66dff",
  sniper: "#f0a53a",
  medic: "#42c97b",
  specialist: "#41c9d6",
};

export const operators: OperatorDefinition[] = [
  {
    id: "amiya",
    name: "阿米娅",
    role: "caster",
    maxHp: 1480,
    attack: 612,
    defense: 121,
    resistance: 20,
    damageType: "arts",
    attackInterval: 1.6,
    attackRangeId: "amiyaDefault",
    rangeTileSize: 54,
    radius: 30,
    speed: 176,
    spRegen: 1,
    skillId: "chimera",
  },
  {
    id: "chen",
    name: "陈",
    role: "guard",
    maxHp: 1480,
    attack: 118,
    defense: 34,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1.3,
    attackRangeId: "forwardShort",
    rangeTileSize: 64,
    radius: 31,
    speed: 188,
    spRegen: 14,
    skillId: "chiXiao",
  },
  {
    id: "hoshiguma",
    name: "星熊",
    role: "defender",
    maxHp: 2050,
    attack: 76,
    defense: 62,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1.6,
    attackRangeId: "forwardShort",
    rangeTileSize: 64,
    radius: 34,
    speed: 142,
    spRegen: 12,
    skillId: "ironWall",
  },
  {
    id: "exusiai",
    name: "能天使",
    role: "sniper",
    maxHp: 1040,
    attack: 82,
    defense: 16,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1,
    attackRangeId: "forwardWide",
    rangeTileSize: 66,
    radius: 27,
    speed: 212,
    spRegen: 22,
    skillId: "overload",
  },
  {
    id: "saria",
    name: "塞雷娅",
    role: "medic",
    maxHp: 1760,
    attack: 70,
    defense: 52,
    resistance: 10,
    damageType: "physical",
    attackInterval: 1.8,
    attackRangeId: "forwardShort",
    rangeTileSize: 64,
    radius: 33,
    speed: 150,
    spRegen: 15,
    skillId: "firstAid",
  },
  {
    id: "phantom",
    name: "傀影",
    role: "specialist",
    maxHp: 1260,
    attack: 91,
    defense: 24,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1.1,
    attackRangeId: "forwardShort",
    rangeTileSize: 64,
    radius: 28,
    speed: 238,
    spRegen: 20,
    skillId: "shadowPush",
  },
];
