import type { OperatorDefinition, OperatorRole } from "./types";

const rangeTileSize = 60;

export const phantomMirrorDefinition: OperatorDefinition = {
  id: "phantomMirror",
  name: "镜中虚影",
  englishName: "The Mirror",
  role: "specialist",
  attackMode: "melee",
  isSummon: true,
  summonOf: "phantom",
  maxHp: 14160,
  attack: 548,
  defense: 268,
  resistance: 0,
  damageType: "physical",
  attackInterval: 0.93,
  attackRangeId: "forwardShort",
  rangeTileSize,
  radius: 25,
  speed: 200,
  spRegen: 0,
  spRecoveryType: "natural",
  skillId: "phantomNightPhantom",
};

export const roleLabels: Record<OperatorRole, string> = {
  guard: "近卫",
  defender: "重装",
  caster: "术师",
  sniper: "狙击",
  medic: "医疗",
  specialist: "特种",
};

export const roleColors: Record<OperatorRole, string> = {
  guard: "#e85858",
  defender: "#6f8faf",
  caster: "#a66dff",
  sniper: "#f0a53a",
  medic: "#42c97b",
  specialist: "#41c9d6",
};

export const operators: OperatorDefinition[] = [
  {
    id: "amiya",
    name: "阿米娅",
    englishName: "Amiya",
    role: "caster",
    attackMode: "ranged",
    maxHp: 1480,
    attack: 612,
    defense: 121,
    resistance: 20,
    damageType: "arts",
    attackInterval: 1.6,
    attackRangeId: "amiyaDefault",
    rangeTileSize,
    radius: 30,
    speed: 200,
    spRegen: 1,
    spRecoveryType: "natural",
    skillId: "chimera",
  },
  {
    id: "chen",
    name: "陈",
    englishName: "Chen",
    role: "guard",
    attackMode: "melee",
    maxHp: 28800,
    attack: 610,
    defense: 352,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1.3,
    attackRangeId: "chenDefault",
    rangeTileSize,
    radius: 31,
    speed: 200,
    spRegen: 0,
    spRecoveryType: "attack",
    attackMultiplier: 1.05,
    defenseMultiplier: 1.05,
    physicalDodge: 0.1,
    skillId: "sheathStrike",
  },
  {
    id: "hoshiguma",
    englishName: "Hoshiguma",
    name: "星熊",
    role: "defender",
    attackMode: "melee",
    maxHp: 38500,
    attack: 430,
    defense: 723,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1.2,
    attackRangeId: "hoshigumaDefault",
    rangeTileSize,
    radius: 34,
    speed: 200,
    spRegen: 1,
    spRecoveryType: "natural",
    defenseMultiplier: 1.06,
    damageBlockChance: 0.25,
    skillId: "hoshigumaWarpath",
  },
  {
    id: "exusiai",
    name: "能天使",
    englishName: "Exusiai",
    role: "sniper",
    attackMode: "ranged",
    maxHp: 16730,
    attack: 540,
    defense: 161,
    resistance: 0,
    damageType: "physical",
    attackInterval: 1,
    attackRangeId: "exusiaiDefault",
    rangeTileSize,
    radius: 27,
    speed: 200,
    spRegen: 1,
    spRecoveryType: "natural",
    attackSpeedBonus: 12,
    attackMultiplier: 1.06,
    maxHpMultiplier: 1.1,
    skillId: "exusiaiOverloadMode",
  },
  {
    id: "saria",
    name: "塞雷娅",
    englishName: "Saria",
    role: "defender",
    attackMode: "melee",
    maxHp: 31500,
    attack: 485,
    defense: 595,
    resistance: 10,
    damageType: "physical",
    attackInterval: 1.2,
    attackRangeId: "sariaDefault",
    rangeTileSize,
    radius: 33,
    speed: 200,
    spRegen: 1,
    spRecoveryType: "natural",
    skillId: "sariaFirstAid",
  },
  {
    id: "phantom",
    englishName: "Phantom",
    name: "傀影",
    role: "specialist",
    attackMode: "melee",
    maxHp: 16450,
    attack: 558,
    defense: 322,
    resistance: 0,
    damageType: "physical",
    attackInterval: 0.93,
    attackRangeId: "forwardShort",
    rangeTileSize,
    radius: 28,
    speed: 200,
    spRegen: 0,
    spRecoveryType: "natural",
    skillId: "phantomNightPhantom",
  },
];

for (const operator of operators) {
  if (
    operator.id !== "chen" &&
    operator.id !== "exusiai" &&
    operator.id !== "saria" &&
    operator.id !== "hoshiguma" &&
    operator.id !== "phantom"
  ) {
    operator.maxHp *= 10;
  }
}
